### ISSUE TITLE
Help for plugin

### ISSUE THREAD

**Issue by SinlesFlyer376** [RTGDaCoder/DiscordBot#1]
I know this has nothing to do with this plugin but can you help me implement this plugin that won't work with someone who knows a bit about coding

**Comment by SinlesFlyer376** [comment]
Dm me on twitter @SinlesFlyer376

**Comment by InspectorGadget** [comment]
Please KIK or Discord me.. I don't use Twitter...

**Comment by SinlesFlyer376** [comment]
Well crap what is your discord?

**Comment by InspectorGadget** [comment]
IG#4095
